Algoritmo "Repetição"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2023
Var
// Seção de Declarações das variáveis
   i :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   i<- 1
   
   enquanto i <= 5 faca
   escreval("valor de 1", i)
   i<-i+1
   fimenquanto

Fimalgoritmo